### ISSUE TITLE
Investigate Excel execution

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Excel_UI#263] opened 2020-10-14 11:02 UTC
#### Description:

Flagging as a bug, not sure if right or not. Also understand if this can be very hard to find a fix for, but:

Excel seem to be executing all of its cells multiple times when you open it/change something in it. Not sure if/Do not think this is something that the Excel_Toolkit has introduced, but is rather an inherent behaviour of how excel is working. 

You can generally spot this when opening a cell with BHoM formulas in it. You can generally see a rapid flickering of GUIDs being updated as the cells are being re-run again and again.

This can become an issue, especially when using adapters. Having excel re-run cells, for example an adapter pull or even worse a push, when a cell that has nothing at all to do with anything related to the adapter can be both unintuitive and dangerous.

Think the issue gets worse when things like Range, IndexOf and similar are being used at all, somewhere in the workbook.

Wonder if there is some way to hook into excels execution tree so that things like creating an adapter, pushing, pulling etc are only executed once when a cell is changed, and even better would be, only when a cell that actually affect any of the inputs to that formula has been changed.

#### Steps to reproduce:

Happens for more or less all BHoM sheets I have, and might be happening for non-BHoM sheets as well, just that it is harder to notice

#### Expected behaviour:

For cells to only be evaluated once each execution cycle and only when something that affects them has changed. Especially critical for adapters.

#### Test file(s):

Behaviour can be spotted in most sheets, but:

https://burohappold.sharepoint.com/:f:/s/BHoM/EiBYGxf-Ql9DiB2Y-EQVkcYBzwpork6YCnveq9GxZamTMQ?e=RiNfPB

**Comment by adecler** [comment] 2021-04-20 05:08
@IsakNaslundBh , my initial findings don't seems to align with what you state above. 

Using the `Loadcases and combinations` files you linked above, I only get a single call to `RemoveNulls` and `Push` when triggering the push (either by updating the cell containing the corresponding `TRUE` or by forcing the `Push` formula to recalculate).

FYI, I use the content of the log for Analytics to check the list of executed methods. You can find the Grasshopper test script here: https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/Excel_Toolkit/ExcelExecutionTest.gh?csf=1&web=1&e=Xi2YNR

I obviously need to investigate further than that specific user example but it might be great if you can provide other examples where you are sure that unnecessary calls to cells are being made.

**Comment by adecler** [comment] 2021-05-15 07:50
@IsakNaslundBh , I have looked into the Excel recalculation engine. A great source of information can be found here: 
http://www.decisionmodels.com/calcsecrets.htm

A key thing to note from that website is that **volatile cells will recalculate every time any cell recalculate**. 

A few things that can be volatile: 
- Formulas like RAND(), NOW(), TODAY(), OFFSET(), CELL(), INDIRECT(), INFO(), RANDBETWEEN(), RANDARRAY()
- Conditional Formats 
- Inserting or Deleting Rows, Columns or Cells, or Moving Cells
- Renaming Worksheets

@tg359 , I noticed during our last meeting that your spreadsheet on building performances seems to take a while to calculate at some point and the cells in your tables appeared as they were flickering. Are you using any of the above volatile options ? Could you send me the file you showed me so I can run some tests as well ?

**Comment by adecler** [comment] 2021-05-25 05:56
@IsakNaslundBh , I am closing this on the assumption that the problem you had was caused by one of the reasons provided above.
I will reopen if there is an actual example that cells are calculated multiple times.

**Closed as completed by adecler** 2021-05-25 05:56 UTC
Labels: type:bug
