### ISSUE TITLE
Dragging Datasets Not Available Upon Download

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Excel_UI#338] opened 2022-03-15 18:49 UTC
Dragging datasets on a downloaded file seemingly works until a method is performed on the dataset (GetProperty):
![image](https://user-images.githubusercontent.com/34316256/158445298-0b65da41-dfe8-4828-9a76-e681c5524189.png)

Upon re-placing the dataset, functions fine:
![image](https://user-images.githubusercontent.com/34316256/158445386-6e038973-4d5d-49e9-94e7-3557fc16f662.png)

Is this expected behaviour? @michaelhoehn have you seen this in LCA tk workflows?

Sample can be found here: https://burohappold.sharepoint.com/sites/Direction/designtechnology/BHoM%20Samples%20Library/Forms/AllItems.aspx?id=%2Fsites%2FDirection%2Fdesigntechnology%2FBHoM%20Samples%20Library%2FMEP%2F00004%5FSpace%20Criteria%20Matrix&viewid=c683ab7e%2D748f%2D4708%2D9132%2Da968b4d1e52b

**Comment by adecler** [comment] 2023-01-10 16:26
@kayleighhoude , can you clarify what the problem is? This is what I get when I open the example file:

![image](https://user-images.githubusercontent.com/16853390/211606858-c0107ea1-e6e1-42ec-8082-aeaff563e563.png)

**Comment by FraserGreenroyd** [comment] 2023-08-25 11:10
I've downloaded the test script today, and opened it with today's alpha and the script has opened successfully so I think this issue can be closed as resolved either by other code or by happenstance.

![image](https://github.com/BHoM/Excel_UI/assets/18049174/cf6bd08e-f721-400b-8ee3-aa2c2bc217ac)

**Closed as completed by FraserGreenroyd** 2023-08-25 11:10 UTC
Labels: type:question
