### ISSUE TITLE
Drop-Down List created by "Create Data" and "Create Enum" not work properly

### ISSUE THREAD

**Issue by WilsonKung** [BHoM/Excel_UI#194] opened 2020-02-01 12:32 UTC
#### Description:
Using BHoM with Excel, when I select "Create Data" in oM Ribbon to create concrete material, the drop-down menu produced only show duplicates of the first item in the list (i.e. C12/15). Similarly, when I select "Create Enum" to create Load Nature, the same situation happens (i.e. Dead).

Could it be an issue with the updated version of Excel (16.0.12325.20280), since earlier versions works fine.

#### How to replicate:
Create Data -> Materials -> MaterialsEurope -> Concrete
Create Enum -> Structure -> Loads -> LoadNature

#### Expected behaviour:
LoadNature drop-down list include Dead, SuperDead, Live, Other etc

#### Test file(s):
[Test File.xlsx](https://github.com/BHoM/Excel_Toolkit/files/4142544/Test.File.xlsx)

**Comment by awakeman** [comment] 2020-02-03 09:33
Thanks for raising I'll look into this ASAP.

**Comment by awakeman** [comment] 2020-02-04 11:17
Can I ask what version of BHoM you are running? if you used an installer it should show up in add or remove programs 
![image](https://user-images.githubusercontent.com/18450341/73740326-e8a72000-473f-11ea-9922-4537df746a69.png)

**Comment by WilsonKung** [comment] 2020-02-16 11:47
Hi Andrew,
I just checked, my BHoM version is 3.0.1.0 (dated 01/02/2020).

**Comment by awakeman** [comment] 2020-02-17 09:32
I have tested with that version and am still unable to reproduce. Could you try deleting the BHoM directory in AppData\Roaming and then reinstall the same version.

**Comment by awakeman** [comment] 2020-02-19 13:02
@WilsonKung Closing this as I can't reproduce either with latest alpha nor the version you are using. Please reopen if you can reliably reproduce and provide steps to do so.

**Closed as completed by awakeman** 2020-02-19 13:02 UTC
Labels: type:bug
