### ISSUE TITLE
Excel_Toolkit: BHoM Addin causes excel to re-open after quit

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/Excel_UI#187] opened 2020-01-27 17:02 UTC
#### Description:
For some users, excel re-opens directly after it's closed. These users installed BHoM 3.0 after the Office 365 update, so I believe it is not related to the upgrade bug we experienced a month or two ago.

#### How to replicate:
Starting from a computer with office 365 installed and no BHoM, install BHoM 3.0 and open Excel. do stuff (non bhom) and then close excel. It will then re-open a second later.

#### Expected behaviour:
Not that

**Comment by rwemay** [comment] 2020-01-27 17:03
Thanks @JosefTaylor , I reported similar, but @awakeman hasn't been able to recreate so far.

**Comment by JosefTaylor** [comment] 2020-01-27 20:50
@rwemay I saw that, but it looks a bit different. I've got two people here who can reliably reproduce, however my excel seems OK. Happy to get them on a screenshare and show off.

**Comment by al-fisher** [comment] 2020-04-01 12:37
To assist with identifying the actual critical issue causing the problem - suggestion on Excel workshop call by @adecler to write _all_ exceptions into log file to filter and mine after the fact

**Comment by maryannewachter** [comment] 2020-06-09 23:18
This is still an issue as of today's alpha build (at least on my machine).

**Comment by al-fisher** [comment] 2020-06-10 09:54
ah - thanks @maryannewachter - timely message :smile: 
actually this long standing PR - now just merged -  https://github.com/BHoM/Excel_Toolkit/pull/208 is now also looking to resolve this issue too. We have been doing some testing the last few days and is looking good.

So will be good for you to look at up coming alphas in next few days/next week to see if crash is still happening for you.

However please do be aware that we, @rwemay and @IsakNaslundBh, are also tweaking the formula representation in excel with a couple of PRs still in the pipe line (including https://github.com/BHoM/Excel_Toolkit/pull/231) so be careful with backwards compatibility over next period too!

**Comment by FraserGreenroyd** [comment] 2020-06-16 16:26
Comments made during  Sprint Kick Off Catch Up this afternoon confirm both @maryannewachter and @BingWangUS are still experiencing this issue in the last 5 days since #208 was merged. More investigation needed potentially.

I will schedule a meeting tomorrow afternoon to get a few heads round this to see what we can work out.

**Comment by JosefTaylor** [comment] 2020-06-16 18:10
my install seems to be OK now, downloaded alpha this morning.

**Comment by BingWangUS** [comment] 2020-06-16 18:20
As suggested by Kayleigh, uninstalled by daily alpha, and re-install after that. Seems working for now. Will report back if the issue came back again.

**Comment by maryannewachter** [comment] 2020-06-16 19:21
I had some other IT problems to sort out, but I can confirm that my AppData folder has been removed and everything seems to be working with today's (6/16) alpha.

**Comment by FraserGreenroyd** [comment] 2020-06-17 17:21
Result of meeting today is that this is still an issue in some small sets of instances. @awakeman and I are trying to resolve it and will report back on another meeting on Friday. Further updates will be posted to the usual channels.

**Comment by adecler** [comment] 2020-09-05 08:45
Should finally be fixed in https://github.com/BHoM/Excel_Toolkit/pull/243

**Closed as completed** 2020-09-10 09:19 UTC
Labels: type:bug
